import type { Event } from "@/types/event";
import { mockClubProfiles } from "@/constants/mockClubProfiles";

export const mockEvents: Event[] = [
  {
    eventId: "event1",
    eventTitle: "AI & Machine Learning Workshop",
    eventPoster: "https://via.placeholder.com/400x250.png?text=AI+Workshop",
    attending: 120,
    hasVolunteerOption: true,
    startDate: "2025-01-20T10:00:00Z",
    duration: "3 hours",
    place: "Innovation Hub",
    desc: "A beginner-friendly workshop introducing the basics of AI and machine learning with hands-on demos.",
    club: mockClubProfiles[0],
    externalLink: "https://example.com/ai-workshop",
    Attendee_points: 10,
    Volunteer_points: 20,
    createdAt: "2024-12-05T09:00:00Z",
  },
  {
    eventId: "event2",
    eventTitle: "Campus Tree Planting Drive",
    eventPoster: "https://via.placeholder.com/400x250.png?text=Tree+Planting",
    attending: 80,
    hasVolunteerOption: true,
    startDate: "2025-02-10T08:30:00Z",
    duration: "5 hours",
    place: "Central Park",
    desc: "Join our mission to make the campus greener by planting 200 new trees!",
    club: mockClubProfiles[1],
    externalLink: "https://example.com/tree-planting",
    Attendee_points: 8,
    Volunteer_points: 15,
    createdAt: "2024-12-15T10:00:00Z",
  },
  {
    eventId: "event3",
    eventTitle: "Digital Art Exhibition 2025",
    eventPoster: "https://via.placeholder.com/400x250.png?text=Digital+Art+Exhibition",
    attending: 150,
    hasVolunteerOption: false,
    startDate: "2025-03-12T17:00:00Z",
    duration: "4 hours",
    place: "Gallery Hall A",
    desc: "Showcasing student artworks and digital media creations from the Art & Design Circle.",
    club: mockClubProfiles[2],
    externalLink: "https://example.com/art-exhibition",
    Attendee_points: 12,
    Volunteer_points: 0,
    createdAt: "2025-01-10T11:00:00Z",
  },
  {
    eventId: "event4",
    eventTitle: "Inter-University Debate Tournament",
    eventPoster: "https://via.placeholder.com/400x250.png?text=Debate+Tournament",
    attending: 200,
    hasVolunteerOption: false,
    startDate: "2025-04-05T09:00:00Z",
    duration: "6 hours",
    place: "Auditorium Hall B",
    desc: "Teams from across universities compete in a day-long tournament on global issues.",
    club: mockClubProfiles[3],
    externalLink: "https://example.com/debate-tournament",
    Attendee_points: 15,
    Volunteer_points: 0,
    createdAt: "2025-02-01T12:00:00Z",
  },
  {
    eventId: "event5",
    eventTitle: "Cultural Food Festival",
    eventPoster: "https://via.placeholder.com/400x250.png?text=Food+Festival",
    attending: 300,
    hasVolunteerOption: true,
    startDate: "2025-05-25T11:00:00Z",
    duration: "7 hours",
    place: "Main Courtyard",
    desc: "A celebration of world cuisines, music, and traditions — open to all students and guests.",
    club: mockClubProfiles[4],
    externalLink: "https://example.com/food-festival",
    Attendee_points: 20,
    Volunteer_points: 25,
    createdAt: "2025-03-05T13:00:00Z",
  },
];
